# Generated by Django 5.2.4 on 2025-09-03 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorlog',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mode',
            field=models.CharField(blank=True, choices=[('hvac', 'HVAC'), ('lighting', 'Lighting'), ('security', 'Security')], max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='offline', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('esp32', 'ESP32'), ('sensor', 'Sensor'), ('actuator', 'Actuator'), ('controller', 'Controller'), ('monitor', 'Monitor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('office', 'Office'), ('lab', 'Laboratory'), ('meeting', 'Meeting Room'), ('storage', 'Storage'), ('corridor', 'Corridor'), ('utility', 'Utility')], max_length=100),
        ),
    ]
