# Generated by Django 5.2.4 on 2025-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorlog',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
