# Generated by Django 5.2.4 on 2025-09-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_equipment_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='offline', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('esp32', 'ESP32'), ('sensor', 'Sensor'), ('actuator', 'Actuator'), ('controller', 'Controller'), ('monitor', 'Monitor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('office', 'Office'), ('lab', 'Laboratory'), ('meeting', 'Meeting Room'), ('storage', 'Storage'), ('corridor', 'Corridor'), ('utility', 'Utility')], max_length=100),
        ),
    ]
