# Generated by Django 5.2.4 on 2025-09-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_sensorlog_options_equipment_device_id_and_more"),
        ("core", "0009_alter_equipment_qr_code_alter_equipment_status_and_more"),
    ]

    operations = []
