# Generated by Django 5.2.4 on 2025-09-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20250903_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='mode',
        ),
    ]
