# Generated by Django 5.2.4 on 2025-09-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_equipment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='mode',
            field=models.CharField(blank=True, choices=[('hvac', 'HVAC'), ('lighting', 'Lighting'), ('security', 'Security')], max_length=100),
        ),
    ]
