# Generated by Django 5.2.4 on 2025-09-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_equipment_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='device_id',
        ),
    ]
