# Generated by Django 5.2.4 on 2025-09-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_equipment_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
