# Generated by Django 5.2.4 on 2025-09-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_equipment_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='mode',
        ),
    ]
