# Generated by Django 5.2.4 on 2025-09-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_maintenancerequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='priority',
        ),
    ]
