# Generated by Django 5.2.4 on 2025-09-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_maintenancerequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='occupancy',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='vacant', max_length=20),
        ),
    ]
