# Generated by Django 5.2.4 on 2025-09-22 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_maintenanceattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlog',
            name='current',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='energy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='voltage',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='HeartbeatLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField()),
                ('dht22_working', models.BooleanField()),
                ('pzem_working', models.BooleanField(default=True)),
                ('success_rate', models.FloatField()),
                ('wifi_signal', models.IntegerField()),
                ('uptime', models.BigIntegerField()),
                ('sensor_type', models.CharField(max_length=100)),
                ('current_temp', models.FloatField()),
                ('current_humidity', models.FloatField()),
                ('current_power', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
