# Generated by Django 5.2.4 on 2025-09-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sensorlog_current_sensorlog_energy_sensorlog_power_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorlog',
            name='light_level',
        ),
        migrations.AddField(
            model_name='heartbeatlog',
            name='photoresistor_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='light_detected',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
