# Generated by Django 5.2.4 on 2025-09-24 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_sensorlog_light_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_per_kwh', models.FloatField()),
                ('time_period', models.CharField(blank=True, help_text="e.g., 'peak:9AM-5PM'", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('pzem', 'PZEM'), ('dht22', 'DHT22'), ('photoresistor', 'Photoresistor'), ('motion', 'Motion Sensor')], max_length=50)),
                ('identifier', models.CharField(help_text='Unique identifier, e.g., PZEM_SERIAL2', max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='offline', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('total_energy', models.FloatField()),
                ('avg_power', models.FloatField()),
                ('peak_power', models.FloatField()),
                ('reading_count', models.IntegerField()),
                ('anomaly_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction', models.TextField(help_text="LLM-generated prediction, e.g., 'PZEM failure likely'")),
                ('confidence', models.FloatField(help_text='Prediction confidence score (0-1)')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddField(
            model_name='heartbeatlog',
            name='failed_readings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heartbeatlog',
            name='pzem_error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heartbeatlog',
            name='voltage_stability',
            field=models.FloatField(blank=True, help_text='Standard deviation of voltage', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='occupancy_pattern',
            field=models.CharField(blank=True, help_text="e.g., '9AM-5PM weekdays'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='typical_energy_usage',
            field=models.FloatField(blank=True, help_text='Typical energy usage in kWh', null=True),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='dht22_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='motion_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='photoresistor_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='pzem_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('temperature_threshold', 'Temperature Threshold'), ('motion', 'Motion Detected'), ('humidity_threshold', 'Humidity Threshold'), ('energy_anomaly', 'Energy Anomaly'), ('predictive_failure', 'Predictive Failure')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='energy_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='light_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='motion_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='heartbeatlog',
            index=models.Index(fields=['equipment', 'recorded_at'], name='core_heartb_equipme_33d6a5_idx'),
        ),
        migrations.AddField(
            model_name='billingrate',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
        migrations.AddField(
            model_name='component',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.equipment'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.component'),
        ),
        migrations.AddIndex(
            model_name='sensorlog',
            index=models.Index(fields=['equipment', 'component', 'recorded_at'], name='core_sensor_equipme_003c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorlog',
            index=models.Index(fields=['component', 'pzem_recorded_at'], name='core_sensor_compone_7f00fd_idx'),
        ),
        migrations.AddField(
            model_name='energysummary',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.component'),
        ),
        migrations.AddField(
            model_name='energysummary',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
        migrations.AddField(
            model_name='predictivealert',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.component'),
        ),
        migrations.AddIndex(
            model_name='billingrate',
            index=models.Index(fields=['room', 'time_period'], name='core_billin_room_id_8f6eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['equipment', 'component_type'], name='core_compon_equipme_09df30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('equipment', 'identifier')},
        ),
        migrations.AddIndex(
            model_name='energysummary',
            index=models.Index(fields=['component', 'period_start', 'period_type'], name='core_energy_compone_ad6812_idx'),
        ),
        migrations.AddIndex(
            model_name='energysummary',
            index=models.Index(fields=['room', 'period_start'], name='core_energy_room_id_e5629e_idx'),
        ),
        migrations.AddIndex(
            model_name='predictivealert',
            index=models.Index(fields=['component', 'triggered_at'], name='core_predic_compone_9a3341_idx'),
        ),
    ]
