# Generated by Django 5.2.4 on 2025-09-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_billingrate_component_energysummary_predictivealert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlog',
            name='reset_flag',
            field=models.BooleanField(default=False),
        ),
    ]
