# Generated by Django 5.2.4 on 2025-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sensorlog_reset_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrate',
            name='currency',
            field=models.CharField(choices=[('PHP', 'Philippine Peso')], default='PHP', max_length=3),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='energy_cost',
            field=models.FloatField(blank=True, help_text='Cost of energy in PHP', null=True),
        ),
        migrations.AlterField(
            model_name='billingrate',
            name='time_period',
            field=models.CharField(blank=True, help_text="e.g., 'peak:09:00-17:00' or 'off-peak:17:00-09:00'", max_length=255, null=True),
        ),
    ]
