# Generated by Django 5.2.4 on 2025-09-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_billingrate_currency_sensorlog_energy_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorlog',
            name='energy_cost',
        ),
    ]
