# Generated by Django 5.2.4 on 2025-09-28 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_sensorlog_energy_cost'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billingrate',
            name='core_billin_room_id_8f6eaa_idx',
        ),
        migrations.RemoveField(
            model_name='billingrate',
            name='time_period',
        ),
        migrations.AddField(
            model_name='billingrate',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time for rate applicability (e.g., 17:00)', null=True),
        ),
        migrations.AddField(
            model_name='billingrate',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time for rate applicability (e.g., 09:00)', null=True),
        ),
        migrations.AddField(
            model_name='billingrate',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Start date for rate validity', null=True),
        ),
        migrations.AddField(
            model_name='billingrate',
            name='valid_to',
            field=models.DateTimeField(blank=True, help_text='End date for rate validity', null=True),
        ),
        migrations.AddField(
            model_name='energysummary',
            name='currency',
            field=models.CharField(choices=[('PHP', 'Philippine Peso')], default='PHP', max_length=3),
        ),
        migrations.AddField(
            model_name='energysummary',
            name='total_cost',
            field=models.FloatField(default=0.0, help_text='Total cost for the period in currency', validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingrate',
            name='rate_per_kwh',
            field=models.FloatField(help_text='Rate per kWh in currency', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddIndex(
            model_name='billingrate',
            index=models.Index(fields=['room', 'start_time', 'end_time'], name='core_billin_room_id_69e65d_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrate',
            index=models.Index(fields=['valid_from', 'valid_to'], name='core_billin_valid_f_e1f76c_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingrate',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time')), ('start_time__isnull', True), ('end_time__isnull', True), _connector='OR'), name='start_time_before_end_time'),
        ),
        migrations.AddConstraint(
            model_name='billingrate',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__lt', models.F('valid_to')), ('valid_from__isnull', True), ('valid_to__isnull', True), _connector='OR'), name='valid_from_before_valid_to'),
        ),
        migrations.AddConstraint(
            model_name='billingrate',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', False), ('start_time__isnull', False), ('valid_from__isnull', False)), fields=('room', 'start_time', 'end_time', 'valid_from', 'valid_to'), name='unique_room_time_validity_period Thing'),
        ),
        migrations.AddConstraint(
            model_name='energysummary',
            constraint=models.CheckConstraint(condition=models.Q(('total_energy__gte', 0)), name='total_energy_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='energysummary',
            constraint=models.CheckConstraint(condition=models.Q(('avg_power__gte', 0)), name='avg_power_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='energysummary',
            constraint=models.CheckConstraint(condition=models.Q(('peak_power__gte', 0)), name='peak_power_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='energysummary',
            constraint=models.CheckConstraint(condition=models.Q(('reading_count__gte', 0)), name='reading_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='energysummary',
            constraint=models.CheckConstraint(condition=models.Q(('anomaly_count__gte', 0)), name='anomaly_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='energysummary',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='total_cost_non_negative'),
        ),
    ]
