# Generated by Django 5.2.4 on 2025-09-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_billingrate_core_billin_room_id_8f6eaa_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billingrate',
            name='unique_room_time_validity_period Thing',
        ),
        migrations.AddConstraint(
            model_name='billingrate',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', False), ('start_time__isnull', False), ('valid_from__isnull', False)), fields=('room', 'start_time', 'end_time', 'valid_from', 'valid_to'), name='unique_room_time_validity_period'),
        ),
    ]
