# Generated by Django 5.2.4 on 2025-10-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_billingrate_unique_room_time_validity_period_thing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('alert', 'Alert'), ('system', 'System')], default='system', max_length=50),
        ),
    ]
