# Generated by Django 5.2.4 on 2025-10-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
